// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolShuttleBus.Infrastructure.Persistence;

#nullable disable

namespace SchoolShuttleBus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchoolShuttleBusDbContext))]
    [Migration("20260317095130_AddChineseCommentsToDomainTables")]
    partial class AddChineseCommentsToDomainTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("點名紀錄識別碼");

                    b.Property<Guid>("AttendanceSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("所屬點名場次識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<string>("EmergencyPhoneSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("緊急聯絡電話快照");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("點名狀態");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("學生識別碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("AttendanceSessionId", "StudentId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords", t =>
                        {
                            t.HasComment("點名紀錄");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.AttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("場次識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid>("CreatedByStaffProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("建立場次的教職員識別碼");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasComment("點名日期");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasComment("行車方向");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasComment("是否已完成點名");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("路線識別碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffProfileId");

                    b.HasIndex("RouteId");

                    b.ToTable("AttendanceSessions", t =>
                        {
                            t.HasComment("點名場次");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("稽核識別碼");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("動作名稱");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("執行者使用者識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("目標實體識別碼");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("目標實體名稱");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("補充資料 JSON");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasComment("稽核紀錄");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.BroadcastAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("公告識別碼");

                    b.Property<int>("Audience")
                        .HasColumnType("int")
                        .HasComment("公告對象");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("公告內容");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("建立公告的使用者識別碼");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("公告主旨");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.ToTable("BroadcastAnnouncements", t =>
                        {
                            t.HasComment("廣播公告");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.DispatchOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("覆寫識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasComment("覆寫日期");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasComment("行車方向");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("指派路線識別碼");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("覆寫狀態");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("學生識別碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StudentId", "Date", "Direction", "Status");

                    b.ToTable("DispatchOverrides", t =>
                        {
                            t.HasComment("派車覆寫設定");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("家長識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("電子郵件");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("家長姓名");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("手機號碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("對應登入使用者識別碼");

                    b.HasKey("Id");

                    b.ToTable("Guardians", t =>
                        {
                            t.HasComment("家長主檔");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("發送紀錄識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("失敗訊息");

                    b.Property<Guid>("NotificationJobId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("所屬通知工作識別碼");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("收件者電子郵件");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("收件者使用者識別碼");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("發送時間（UTC）");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("發送狀態");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("NotificationJobId");

                    b.ToTable("NotificationDeliveries", t =>
                        {
                            t.HasComment("通知發送紀錄");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.NotificationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("通知工作識別碼");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("通知內容");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasComment("發送管道");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("建立通知的使用者識別碼");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("工作類型");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("通知主旨");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.ToTable("NotificationJobs", t =>
                        {
                            t.HasComment("通知工作");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("範本識別碼");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("通知內容");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("通知主旨");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("範本名稱");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplates", t =>
                        {
                            t.HasComment("通知範本");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("匯出識別碼");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("匯出內容");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("內容類型");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("建立匯出的使用者識別碼");

                    b.Property<int>("ExportFormat")
                        .HasColumnType("int")
                        .HasComment("匯出格式");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("檔名");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("匯出條件 JSON");

                    b.Property<int>("ReportType")
                        .HasColumnType("int")
                        .HasComment("報表類型");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.ToTable("ReportExports", t =>
                        {
                            t.HasComment("報表匯出紀錄");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.RideRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("登記識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasComment("搭車日期");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasComment("行車方向");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit")
                        .HasComment("是否實際到場搭乘");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit")
                        .HasComment("是否已登記搭車");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("指派路線識別碼");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("學生識別碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StudentId", "Date", "Direction")
                        .IsUnique();

                    b.ToTable("RideRegistrations", t =>
                        {
                            t.HasComment("搭車登記資料");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("路線識別碼");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("校區名稱");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasComment("行車方向");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("是否啟用");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("路線名稱");

                    b.Property<int>("RouteType")
                        .HasColumnType("int")
                        .HasComment("路線類型");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.ToTable("Routes", t =>
                        {
                            t.HasComment("校車路線主檔");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.RouteAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("指派識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("路線識別碼");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("教職員識別碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("RouteAssignments", t =>
                        {
                            t.HasComment("路線指派資料");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("站點識別碼");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("站點地址");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<string>("HandoffContactName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("交接聯絡人姓名");

                    b.Property<string>("HandoffContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("交接聯絡人電話");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("所屬路線識別碼");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasComment("停靠順序");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("站點名稱");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "Sequence")
                        .IsUnique();

                    b.ToTable("RouteStops", t =>
                        {
                            t.HasComment("路線停靠站");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("教職員識別碼");

                    b.Property<bool>("CanManageAllRoutes")
                        .HasColumnType("bit")
                        .HasComment("是否可管理全部路線");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("工號");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("教職員姓名");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聯絡電話");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("對應登入使用者識別碼");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("StaffProfiles", t =>
                        {
                            t.HasComment("教職員主檔");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("學生識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid?>("DefaultRouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("預設路線識別碼");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("學生姓名");

                    b.Property<string>("GradeLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("年級標籤");

                    b.Property<int>("Stage")
                        .HasColumnType("int")
                        .HasComment("學制階段");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("學號");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("對應登入使用者識別碼");

                    b.HasKey("Id");

                    b.HasIndex("DefaultRouteId");

                    b.ToTable("Students", t =>
                        {
                            t.HasComment("學生主檔");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.StudentGuardianLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("關聯識別碼");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("建立時間（UTC）");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("家長識別碼");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit")
                        .HasComment("是否為主要聯絡人");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("學生識別碼");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("最後更新時間（UTC）");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.HasIndex("StudentId", "GuardianId")
                        .IsUnique();

                    b.ToTable("StudentGuardianLinks", t =>
                        {
                            t.HasComment("學生與家長關聯");
                        });
                });

            modelBuilder.Entity("SchoolShuttleBus.Infrastructure.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SchoolShuttleBus.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("權杖識別碼");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("到期時間（UTC）");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("撤銷時間（UTC）");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("權杖字串");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("對應使用者識別碼");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasComment("重新整理權杖");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SchoolShuttleBus.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SchoolShuttleBus.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolShuttleBus.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SchoolShuttleBus.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.AttendanceSession", "AttendanceSession")
                        .WithMany("Records")
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolShuttleBus.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.AttendanceSession", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.StaffProfile", "CreatedByStaffProfile")
                        .WithMany()
                        .HasForeignKey("CreatedByStaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolShuttleBus.Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByStaffProfile");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.DispatchOverride", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolShuttleBus.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.NotificationJob", "NotificationJob")
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationJob");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.RideRegistration", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.HasOne("SchoolShuttleBus.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.RouteAssignment", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.Route", "Route")
                        .WithMany("Assignments")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolShuttleBus.Domain.Entities.StaffProfile", "StaffProfile")
                        .WithMany("RouteAssignments")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.Route", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Student", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.Route", "DefaultRoute")
                        .WithMany()
                        .HasForeignKey("DefaultRouteId");

                    b.Navigation("DefaultRoute");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.StudentGuardianLink", b =>
                {
                    b.HasOne("SchoolShuttleBus.Domain.Entities.Guardian", "Guardian")
                        .WithMany("StudentLinks")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolShuttleBus.Domain.Entities.Student", "Student")
                        .WithMany("GuardianLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolShuttleBus.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.HasOne("SchoolShuttleBus.Infrastructure.Auth.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.AttendanceSession", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Guardian", b =>
                {
                    b.Navigation("StudentLinks");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.NotificationJob", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Route", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.StaffProfile", b =>
                {
                    b.Navigation("RouteAssignments");
                });

            modelBuilder.Entity("SchoolShuttleBus.Domain.Entities.Student", b =>
                {
                    b.Navigation("GuardianLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
